cidade = input("Qual é a cidade o nome da cidade que você cresceu: ")
print(f"Você cresceu em {cidade}")
animal_estimação = input("Qual o nome do seu animal de estimação: ")
print(f"Seu animal de estimmação se chama {animal_estimação}")
print(f"Sua banda pode ser chamada de {cidade} + {animal_estimação}")